import crypto from 'crypto';
import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createClient as createAdminClient } from '@supabase/supabase-js';
import { logger } from '@/lib/logging';
import { inngest } from '@/lib/inngest/client';
import { getUserLocale } from '@/lib/i18n/get-user-locale';

const supabaseAdmin = createAdminClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: NextRequest) {
    const requestId = crypto.randomUUID();

    try {
        // §8: Auth Guard
        const supabase = await createClient();
        const { data: { user }, error: authError } = await supabase.auth.getUser();
        if (authError || !user) {
            return NextResponse.json({ error: 'Unauthorized', requestId }, { status: 401 });
        }

        const log = logger.forRequest(requestId, user.id, '/api/video/upload');
        const { jobId, action, mimeType } = await request.json() as {
            jobId: string;
            action: 'get-signed-url' | 'confirm-upload';
            mimeType?: string; // e.g. 'video/webm;codecs=vp9', 'video/mp4'
        };

        if (!jobId || !action) {
            return NextResponse.json({ error: 'Missing jobId or action', requestId }, { status: 400 });
        }

        const userId = user.id;

        if (action === 'get-signed-url') {
            log.info('Generating signed upload URL', { jobId });

            // Check existing entry -- if storage_path exists, delete old file first (re-record cleanup)
            const { data: existing } = await supabaseAdmin
                .from('video_approaches')
                .select('storage_path')
                .eq('user_id', userId)
                .eq('job_id', jobId)
                .maybeSingle();

            if (existing?.storage_path) {
                log.info('Deleting old video before re-upload', { path: existing.storage_path });
                await supabaseAdmin.storage
                    .from('videos')
                    .remove([existing.storage_path]);
            }

            // Derive extension from browser-reported MIME type.
            // Safari records video/mp4; Chrome/FF record video/webm.
            // Storing the correct extension is critical for playback signed URLs.
            const ext = mimeType?.includes('mp4') ? 'mp4' : 'webm';
            const storagePath = `${userId}/${jobId}.${ext}`;
            const { data: signedData, error: signedError } = await supabaseAdmin.storage
                .from('videos')
                .createSignedUploadUrl(storagePath);

            if (signedError || !signedData) {
                log.error('Failed to create signed upload URL', { error: signedError?.message });
                return NextResponse.json({ error: 'Signed URL creation failed', requestId }, { status: 500 });
            }

            // UPSERT: Guarantee the video_approaches row exists.
            // The Script Studio flow writes to video_scripts but never creates
            // a video_approaches row. Without this upsert, the confirm-upload
            // UPDATE would silently affect 0 rows and the video stays unlinked.
            // access_token is auto-generated by DB default (gen_random_uuid()).
            const { error: upsertError } = await supabaseAdmin
                .from('video_approaches')
                .upsert(
                    {
                        user_id: userId,
                        job_id: jobId,
                        storage_path: storagePath,
                        updated_at: new Date().toISOString(),
                    },
                    { onConflict: 'user_id,job_id', ignoreDuplicates: false }
                );

            if (upsertError) {
                log.error('Failed to upsert video_approaches', { error: upsertError.message });
                return NextResponse.json({ error: 'DB write failed', requestId }, { status: 500 });
            }

            return NextResponse.json({
                success: true,
                requestId,
                signedUrl: signedData.signedUrl,
                token: signedData.token,
                storagePath,
            });

        } else if (action === 'confirm-upload') {
            log.info('Confirming video upload', { jobId, mimeType: mimeType || 'not-sent' });

            const expiresAt = new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString();
            // Safety: re-set storage_path atomically here to handle edge cases
            // where the get-signed-url DB write was not yet committed.
            // Use correct extension from mimeType — Safari uses mp4.
            const ext = mimeType?.includes('mp4') ? 'mp4' : 'webm';
            const storagePath = `${userId}/${jobId}.${ext}`;

            // UPSERT as defense-in-depth: if get-signed-url's upsert
            // failed or was skipped, this still creates the row.
            const { error: updateError } = await supabaseAdmin
                .from('video_approaches')
                .upsert(
                    {
                        user_id: userId,
                        job_id: jobId,
                        status: 'uploaded',
                        storage_path: storagePath,
                        uploaded_at: new Date().toISOString(),
                        expires_at: expiresAt,
                        updated_at: new Date().toISOString(),
                    },
                    { onConflict: 'user_id,job_id', ignoreDuplicates: false }
                );

            if (updateError) {
                log.error('Failed to confirm upload', { error: updateError.message });
                return NextResponse.json({ error: 'Upload confirmation failed', requestId }, { status: 500 });
            }

            // §1 Double-Assurance: Read-Back verification
            const { data: verify } = await supabaseAdmin
                .from('video_approaches')
                .select('status, access_token')
                .eq('user_id', userId)
                .eq('job_id', jobId)
                .single();

            if (!verify || verify.status !== 'uploaded') {
                log.error('Double-Assurance failed — status not uploaded after update');
                return NextResponse.json({ error: 'Upload verification failed', requestId }, { status: 500 });
            }

            // §3 Guarantee: access_token must never be null.
            // gen_random_uuid() default only fires on INSERT, not on UPSERT update.
            // If somehow null (e.g. old row without token), generate one here.
            let finalToken = verify.access_token;
            if (!finalToken) {
                finalToken = crypto.randomUUID();
                await supabaseAdmin
                    .from('video_approaches')
                    .update({ access_token: finalToken, updated_at: new Date().toISOString() })
                    .eq('user_id', userId)
                    .eq('job_id', jobId);
                log.info('access_token was null — generated and saved', { finalToken });
            }

            // Fire Inngest scheduled deletion
            await inngest.send({
                name: 'video/schedule-deletion',
                data: { userId, jobId, locale: await getUserLocale(userId) },
            });

            log.info('Video upload confirmed, deletion scheduled', { expiresAt });

            return NextResponse.json({
                success: true,
                requestId,
                expiresAt,
                accessToken: finalToken,
            });
        }

        return NextResponse.json({ error: 'Invalid action', requestId }, { status: 400 });

    } catch (error: unknown) {
        const errMsg = error instanceof Error ? error.message : String(error);
        console.error(`[${requestId}] ❌ video/upload error=${errMsg}`);
        return NextResponse.json({ error: errMsg || 'Upload failed', requestId }, { status: 500 });
    }
}
